title: Software Everything
url: https://pawel.ie
description: >

minima:
    social-links:
      email:
      github: kurdybacha/pawel.ie
      linkedin: https://www.linkedin.com/in/kurdybacha 
      twitter: kurdybacha

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
