title: All Things Software
url: https://pawel.ie
author: Pawel Kurdybacha
description: >

github_username:  kurdybacha
linkedin_username: kurdybacha

google_analytics: UA-140013744-1

minima:
    social_links:
      email:
      github: kurdybacha
      linkedin: kurdybacha

theme: minima
  skin: dark

disqus:
    shortname: github_comments_with_utterances

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
